#!/bin/bash

set -euo pipefail

cd repo-git

GIT_REPO=$(git config --get remote.origin.url)

PR_NAME="Promote from ${BRANCH} to ${PROMOTION_BRANCH}"

if [ "${BRANCH}" = "${PROMOTION_BRANCH}" ]; then
  echo "🚫 Branch and promotion branch are both ${BRANCH}, no PR required"
  exit 0
fi

echo "${GITHUB_AUTH}" | gh auth login --with-token

if gh pr list --limit 999 \
  --state open \
  --base "${PROMOTION_BRANCH}" \
  --repo "${GIT_REPO}" | grep -q "${PR_NAME}"; then
  echo "⏭️ PR already exists for ${PR_NAME}, skipping..."
  exit 0
fi

echo "📤 Creating PR from ${BRANCH} to ${PROMOTION_BRANCH}..."

if gh pr create --title "${PR_NAME}" \
  --reviewer ONSdigital/blaise5 \
  --base "${PROMOTION_BRANCH}" \
  --head "${BRANCH}" \
  --body "Auto generated by concourse:"$'\n\n'"${PR_NAME}" | grep -q "No commits"; then
  echo "⏭️ No commits between ${BRANCH} and ${PROMOTION_BRANCH}, not raising PR"
else
  echo "✅ Raised PR for promotion from ${BRANCH} to ${PROMOTION_BRANCH}"
fi
