---
github_auth: &github_auth
  username: ((github_pat))
  password: x-oauth-basic

aws_auth: &aws_auth
  AWS_ACCESS_KEY_ID: ((aws.access_key))
  AWS_SECRET_ACCESS_KEY: ((aws.secret_key))

groups:
- name: all
  jobs:
  - "*"

- name: terraform
  jobs:
  - terraform-plan
  - terraform-apply

resource_types:
- name: terraform
  type: docker-image
  source:
    repository: ljfranklin/terraform-resource
    tag: latest

- name: pull-request
  type: docker-image
  source:
    repository: teliaoss/github-pr-resource

resources:
  - name: repo-git
    type: git
    source:
      <<: *github_auth
      uri: https://github.com/onsdigital/((git.repo))
      branch: ((git.branch.repo-git))

  - name: pull-request
    type: pull-request
    check_every: 30s
    webhook_token: ((github_pat))
    source:
      repository: onsdigital/((git.repo))
      access_token: ((github_pat))
      base_branch: ((git.branch.repo-git-pr))
      ignore_drafts: false


jobs:
  - name: hello-world
    plan:
    - get: repo-git
      trigger: true

    - task: hello-world
      file: repo-git/HelloWorld/HelloWorld.yml