---
github_auth: &github_auth
  username: ((github_pat))
  password: x-oauth-basic

aws_auth: &aws_auth
  AWS_ACCESS_KEY_ID: ((aws.access_key))
  AWS_SECRET_ACCESS_KEY: ((aws.secret_key))

groups:
- name: all
  jobs:
  - "*"


resource_types:
- name: terraform
  type: docker-image
  source:
    repository: ljfranklin/terraform-resource
    tag: latest

resources:
  - name: repo-git
    type: git
    source:
      <<: *github_auth
      uri: https://github.com/onsdigital/((git.repo))
      branch: ((git.branch.repo-git))


jobs:
  - name: hello-world
    plan:
    - get: repo-git
      trigger: true

    - task: hello-world
      file: repo-git/HelloWorld/HelloWorld.yml