---
github_auth: &github_auth
  username: ((github_pat))
  password: x-oauth-basic

aws_auth: &aws_auth
  AWS_ACCESS_KEY_ID: ((aws.access_key))
  AWS_SECRET_ACCESS_KEY: ((aws.secret_key))

groups:
  - name: all
    jobs:
      - "*"

resource_types:
  - name: terraform
    type: docker-image
    source:
      repository: ljfranklin/terraform-resource
      tag: latest

  - name: pull-request
    type: docker-image
    source:
      repository: teliaoss/github-pr-resource

resources:
  - name: repo-git
    type: git
    source:
      <<: *github_auth
      uri: https://github.com/onsdigital/((git.repo))
      branch: ((git.branch))

  - name: pull-request
    type: pull-request
    icon: source-pull
    webhook_token: ((github_pat))
    source:
      repository: onsdigital/((git.repo))
      access_token: ((github_pat))
      base_branch: ((git.branch))
      ignore_drafts: false


jobs:
  # Terraform pipeline
  - name: set-pipeline-pr
    plan:
      - get: pull-request
        trigger: true
      - set_pipeline: self # pipeline's name
        file: pull-request/ci/pipeline.yml
        var_files:
          - pull-request/ci/env/((concourse.vars))

  - name: unit-tests
    plan:
      - get: pull-request
        trigger: true
        passed: [set-pipeline-pr]

      - task: run-unit-tests
        input_mapping:
          repo-git: pull-request
        file: pull-request/ci/tasks/unitTests/task.yml
        on_failure:
          put: pull-request
          params:
            path: pull-request
            status: FAILURE

  - name: terraform-plan
    plan:
      - get: pull-request
        trigger: true
        passed: [unit-tests]

      - put: pull-request
        params:
          path: pull-request
          status: pending

      - task: terraform-plan
        file: pull-request/ci/tasks/terraform/terraform-plan.yml
        vars:
          access_key: ((aws.access_key))
          secret_key: ((aws.secret_key))
          backend_role: ((aws.backend_role))
        params:
          S3_BUCKET_NAME: ((aws.s3_bucket))
          TF_STATE: ((aws.tfstate))
          TF_LOCKS: ((aws.tflocks))
          GIT_PAT: ((github_pat))
          TF_VARS: ((terraform.tfvars))
          AWS_ACCESS_KEY_ID: ((aws.access_key))
          AWS_SECRET_ACCESS_KEY: ((aws.secret_key))
          BACKEND_ROLE_ARN: ((aws.backend_role))
        on_failure:
          put: pull-request
          params:
            path: pull-request
            status: FAILURE

      - in_parallel:
          - task: linting
            file: pull-request/ci/tasks/tflint/task.yml
            input_mapping:
              repo-git: pull-request
            params:
              S3_BUCKET_NAME: ((aws.s3_bucket))
              TF_STATE: ((aws.tfstate))
              AWS_ACCESS_KEY_ID: ((aws.access_key))
              AWS_SECRET_ACCESS_KEY: ((aws.secret_key))
            on_failure:
              put: pull-request
              params:
                path: pull-request
                status: FAILURE

          - task: trivy
            file: pull-request/ci/tasks/trivy/task.yml
            input_mapping:
              repo-git: pull-request
            params:
              GIT_PAT: ((github_pat))
            on_failure:
              put: pull-request
              params:
                path: pull-request
                status: FAILURE

          - task: checkov
            file: pull-request/ci/tasks/checkov/task.yml
            input_mapping:
              repo-git: pull-request
            on_failure:
              put: pull-request
              params:
                path: pull-request
                status: FAILURE

          - task: gitleaks
            file: pull-request/ci/tasks/gitleaks/task.yml
            input_mapping:
              repo-git: pull-request
            on_failure:
              put: pull-request
              params:
                path: pull-request
                status: FAILURE

          - task: trufflehog
            file: pull-request/ci/tasks/trufflehog/task.yml
            input_mapping:
              repo-git: pull-request
            on_failure:
              put: pull-request
              params:
                path: pull-request
                status: FAILURE

      - put: pull-request
        params:
          path: pull-request
          status: success

  - name: set-pipeline
    plan:
      - get: repo-git
        trigger: true
      - set_pipeline: self # pipeline's name
        file: repo-git/ci/pipeline.yml
        var_files:
          - repo-git/ci/env/((concourse.vars))

  - name: terraform-apply
    plan:
      - get: repo-git
        trigger: true
        passed: [set-pipeline]
      - get: pull-request
        trigger: false
        passed: [terraform-plan]

      - task: terraform-apply
        file: repo-git/ci/tasks/terraform/terraform-apply.yml
        vars:
          access_key: ((aws.access_key))
          secret_key: ((aws.secret_key))
          backend_role: ((aws.backend_role))
        params:
          S3_BUCKET_NAME: ((aws.s3_bucket))
          TF_STATE: ((aws.tfstate))
          TF_LOCKS: ((aws.tflocks))
          GIT_PAT: ((github_pat))
          TF_VARS: ((terraform.tfvars))
          AWS_ACCESS_KEY_ID: ((aws.access_key))
          AWS_SECRET_ACCESS_KEY: ((aws.secret_key))
          BACKEND_ROLE_ARN: ((aws.backend_role))

  - name: uploader-behaviour-tests
    plan:
      - get: repo-git
        trigger: true
        passed: [terraform-apply]
      - task: run-behaviour-tests
        input_mapping:
          repo-git: repo-git
        file: repo-git/ci/tasks/behaviourTests/task.yml

  - name: uploader-performance-tests
    plan:
      - get: repo-git
        trigger: true
        passed: [uploader-behaviour-tests]

      - task: run-uploader-performance-tests
        input_mapping:
          repo-git: repo-git
        file: repo-git/ci/tasks/performanceTests/task.yml
        params:
          ENV: dev
        on_failure:
          put: pull-request
          params:
            path: pull-request
            status: FAILURE
