upload_host_bucket_name   = "aws-uploader-ost-dev"
upload_ingest_bucket_name = "aws-uploader-ingest-ost-dev"
cloudfront_logging_bucket = "cloudfront-logging-ost-dev"
domain_name               = "ingest-dev.aws.onsdigital.uk"
sqs_notification_id       = "nifi-s3-sqs-notification"