upload_host_bucket_name   = "aws-uploader-ost-preprod"
upload_ingest_bucket_name = "aws-uploader-ingest-ost-preprod"
cloudfront_logging_bucket = "cloudfront-logging-ost-preprod"
domain_name               = "ingest-preprod.aws.onsdigital.uk"
sqs_notification_id       = "nifi-s3-sqs-notification"