environment               = "prod"
upload_host_bucket_name   = "aws-uploader-ost-prod"
upload_ingest_bucket_name = "aws-uploader-ingest-ost-prod"
cloudfront_logging_bucket = "cloudfront-logging-ost-prod"
domain_name               = "ingest.aws.onsdigital.uk"
sqs_notification_id       = "nifi-s3-sqs-notification"
target_account_id         = "732316826607"
